### ISSUE TITLE
Output: HTML Charset

### ISSUE THREAD

**Issue by dustalov** [h3rald/glyph#133]
Please, let Glyph put `<meta http-equiv="content-type" content="text/html; charset=utf-8" />` tag at HTML document, because of troubles in publishing (e.g. Russian characters).

**Comment by h3rald** [comment]
Agreed, will fix it asap, it's just a line to add to te head macro :-)

**Comment by h3rald** [comment]
Closed by b7982ce5443fe84edfe9ee82b087ed790df39fda.
