### ISSUE TITLE
 ../bin/glyph compile -f odf --debug  debug option isn't recognized

### ISSUE THREAD

**Issue by epugh** [h3rald/glyph#137]
This is with trunk of glyph...

budapest-3:bob epugh$ ../bin/glyph compile -f odf --debug
error: Unknown argument -

**Comment by h3rald** [comment]
The correct syntax should be:

<code>glyph --debug compile -f odf</code>

...as debug is a global option. Then you'll get another error because odf is not a supported format, but that's another story altogether.

**Comment by h3rald** [comment]
Closed as "no bug" for now.
