### ISSUE TITLE
Requirement for empty directory conflicts with Bundler

### ISSUE THREAD

**Issue by stuartellis** [h3rald/glyph#145]
I've installed Glyph 0.3.0 successfully with Bundler 1.0 RC2, but the presence of the Bundler Gemfile means that glyph init will not run in the root directory.

If you use a subdirectory for the Glyph project, then "bundle exec glyph init" runs correctly.

**Comment by h3rald** [comment]
Thanks! I'll look into it...

**Comment by stuartellis** [comment]
In case it helps, I've just updated the public copy of the repository:

http://github.com/stuartellis/jruby_quickstart

**Comment by h3rald** [comment]
Thanks a lot, I'll take a look at it tomorrow (i.e. in 12 hours or so).

**Comment by h3rald** [comment]
Closed by e55267ad76105890f4c9.

**Comment by stuartellis** [comment]
The glyph init command was blocking on the Gemfile.lock that Bundler also creates, so I've amended the regular expression to allow Gemfile\* and also Rakefile, and sent you a pull request. I guess that if the number of names grows further this might be better as a white-list...

**Comment by h3rald** [comment]
Pulled, thanks a lot!
