### ISSUE TITLE
[dev] Error on document compile with 0.4.0 development version

### ISSUE THREAD

**Issue by stuartellis** [h3rald/glyph#146]
Using the Glyph version from commit 452af3675335676e775c, document compilation fails with this message:

error: can't convert nil into String

(There's no other output)

The document builds successfully with the Glyph 0.3.0 gem.

The source for the Glyph project is here: http://github.com/stuartellis/jruby_quickstart/tree/61fb6a2129eedaa605919143525e8b273250889c/jruby_quickstart

**Comment by h3rald** [comment]
Thanks! Could you try a <code>glyph --debug compile</code>? That should provide at least the backtrace.

The current development version (i.e. what's in /master right now) is not throughly tested yet. Unit tests pass, but that's by no means enough: normally a lot of bugs show up when I try using it properly (i.e. I update and recompile the Glyph book).

From next release onwards, I'll probably keep new features out of /master, or have a separate branch for hotfixes, to avoid potential problems.

P.S.: Happy to see you chose Glyph for your JRuby QuickStart! If you have any questions, feel free to ask, post in the user group or simply open bugs (but you already know how to do that :P).

**Comment by stuartellis** [comment]
Thanks - I used a DocBook toolchain the last time that I wrote technical documentation, and Glyph looks so much better.

I've just pushed a new branch called se/glyph-devel which is attached to that commit. The backtrace with --debug is now here:

http://gist.github.com/505980

I think that I'll keep the master branch on stable Glyph releases, and run that glyph-devel branch on development versions. Please feel free to use it if you need another document for testing or anything.

**Comment by h3rald** [comment]
Fixed bug in compile command (document.output read when config wasn't loaded yet).
- Closed by 799c8433d78c00655264fc6566d61aa8dbacb0f8.

**Comment by h3rald** [comment]
Thanks a lot! I'll definitely keep an eye on your project and use it for additional tests!
