### ISSUE TITLE
[dev] Gemspec is technically not valid

### ISSUE THREAD

**Issue by stuartellis** [h3rald/glyph#150]
This is with commit e8e0756. The rake:build task works OK and claims that the spec is valid, but Bundler reports this warning from parsing the gemspec:

http://gist.github.com/514650

The rake gemspec:validate task isn't working to test the gemspec inside the project (I'll file a separate issue for that).

**Comment by h3rald** [comment]
Yup, that's right... I was going to version the book/output/html5/\* files but changed my mind at the last minute: I guess I didn't regenerate the gemspec though.

**Comment by h3rald** [comment]
Fixed gemspec + other minor bugs in html5/web5 output.
- Closed by 140bb40a5f89f707a77db8fe37b5c8a2b85af74e.
