### ISSUE TITLE
Rake task for Gemspec Validation Is Broken

### ISSUE THREAD

**Issue by stuartellis** [h3rald/glyph#151]
If you run: rake gemspec:validate --trace

It throws this error:

http://gist.github.com/514661

The same error occurs with both commit e8e0756 (0.4.0dev) and tag 0.3.0.

It might be this bug in Jeweler itself:

http://github.com/technicalpickles/jeweler/issues/issue/81

**Comment by h3rald** [comment]
It definitely looks like a bug in Jeweler... I'll keep an eye on it.
