### ISSUE TITLE
wkhtmltopdf Produces Tiny Pages

### ISSUE THREAD

**Issue by stuartellis** [h3rald/glyph#153]
This is with commit 67a344 and wkhtmltopdf 0.1.2 gem.

If you set a Glyph project to use wkhtmltopdf it will generate the PDF and the pages will be the correct size but the content on them will be very, very small. This occurs with the Glyph book project as well as my own project.

**Comment by h3rald** [comment]
Most likely a stylesheet problem. Which stylesheets did you include? Try disabling the css3.css one.

**Comment by h3rald** [comment]
I looked into this. 

DO NOT install the gem, as it probably packs an old version of wkhtmltopdf. Install wkhtmltopdf from source (0.10.0_beta4) from http://code.google.com/p/wkhtmltopdf/ and it works reasonably well. 

It's not Prince and it has some minor problems, but the result is more than acceptable!

**Comment by stuartellis** [comment]
You are absolutely right - although the gem was updated this year, it actually contains wkhtmltopdf 0.8.3. Version 0.10.0_beta4 does the trick.

Thanks!
