### ISSUE TITLE
PDF Output Generator Is Locked To wkhtmltopdf

### ISSUE THREAD

**Issue by stuartellis** [h3rald/glyph#154]
Observed commit 67a344.

When Glyph reaches this line in the generate task, Glyph['output.pdf.generator'] is always 'wkhtml2pdf', even if the setting tools.pdf_generator is defined and set to 'prince'.

http://github.com/h3rald/glyph/blob/master/tasks/generate.rake#L144

**Comment by h3rald** [comment]
The tools.\* configuration hash has been deprecated altogether (see issue #139). Therefore tools.pdf_generator has no effect; you should use output.pdf.generator instead... Does it work?

**Comment by h3rald** [comment]
Tested myself. It seems to work as expected by setting output.pdf.generator to prince/ wkhtmltopdf.

**Comment by h3rald** [comment]
Closed as no bug.
