### ISSUE TITLE
Link to book on wiki page is to 0.1.0, not 0.3.0 version

### ISSUE THREAD

**Issue by epugh** [h3rald/glyph#167]
Shouldn't the link http://github.com/h3rald/glyph/wiki be to the 0.3.0 version?  Didn't want to fix it without double checking!

**Comment by h3rald** [comment]
Thanks! Yes, it should.

Fixed now. The correct (and version independent) link now points to:

http://github.com/downloads/h3rald/glyph/glyph.pdf

...which is for the (upcoming) 0.4.0 version (due either tomorrow or saturday!).
