### ISSUE TITLE
E-book creation from HTML output

### ISSUE THREAD

**Issue by tammymakesthings** [h3rald/glyph#180]
It would be most handy to be able to create e-books (.epub and .mobi are the most common file formats, I think) from the HTML generated by Glyph. Although there are probably libraries which create these kinds of files directly from Ruby, I think that the fastest way to implement this feature (although one which would require an external dependency) would be to rely on Calibre (http://www.calibre-ebook.com/) to do the HTML-to-ebook transformation.

Changes I can see needing to make this work are relatively few:
- Something would need to be added (to the config.yml, perhaps?) specifying the name of the image to be used as the cover art for the e-book, and
- A rake task or two would need to be added which can do the html to epub and html to mobi conversion using Calibre

I'd be happy to work on this, if there's interest.

**Comment by h3rald** [comment]
I agree, creating ebooks from Glyph's HTML would be great!

I have no problems with external dependencies, especially if they are cross-platform and open source like Calibre. Indeed it seems easy enough. I had a quick look  at Calibre User Manual and if I understood it right all you need to do is wrap the ebook-convert command!

Additionally, it would be fairly easy to support not only the cover, but any of Calibre options through Glyph's configuration. You could, for example, think about having a output.epub.\* hash with Calibre's HTML-to-EPUB options and so on.

Then yes, a simple rake task would do the trick...

Feel free to work on this, you can fork and send pull requests :-) -- If you don't I will definitely implement it anyway :P

**Comment by tammymakesthings** [comment]
I will work on this and see how far I get.

**Comment by h3rald** [comment]
Fixed images/css in epub/mobi output
- Closed by 14dfc5103c8e4978f00fb7b47c361f0ee8442d56.
