### ISSUE TITLE
prince: command not found

### ISSUE THREAD

**Issue by blambeau** [h3rald/glyph#191]
When we run glyph for the first time without knowing it at all, the generation fails.

On ruby-compendium:

<pre>
-- Parsing: document.glyph
-- Processing...
-- Post-processing...
-- Copying images...
-- Generating HTML file...
-- 'ruby-compendium.html' generated successfully.
-- Generating PDF file...
sh: prince: command not found
=> error: An error occurred while generating ruby-compendium.pdf
</pre>

What is prince ??

**Comment by h3rald** [comment]
To generate a PDF with Glyph, you need either of the following:
- [Prince XML](http://www.princexml.com/) -- free for non-commercial use, good CSS3 support, generates nice PDFs) 
- [wkhtmltopdf](http://code.google.com/p/wkhtmltopdf/) -- GPL3-licensed, CSS3 support is not so great, but PDFs are decent.

Just install Prince and re-run glyph compile.

For the Ruby compendium I set "prince" as the default PDF generator... but you can change the config.yml and use wkhtmltopdf if you prefer!

For Glyph documentation, see http://www.h3rald.com/glyph/book/

**Comment by h3rald** [comment]
Closed (no bug, behavior explained in the documentation).
