### ISSUE TITLE
default.css not being generated

### ISSUE THREAD

**Issue by Jabbslad** [h3rald/glyph#93]
The documentation mentions following:-

"Within head[], the style[] macro is used to load the default.css stylesheet, which is included
by default the /styles directory of every Glyph project."

No default.css seems to be created in the styles/ dir so when I compile the project it fails. 

macbookpro:test jabbslad$ glyph -d compile
Loading snippets...
Loading macros...
Parsing 'document.glyph'...
Processing...
Stylesheet 'default.css' not found
 -> source: file: document.glyph
 -> path: document/head/style
macbookpro:test jabbslad$

**Comment by Jabbslad** [comment]
I can work around this by creating my own default.css but just wondered if this was expected or not as documentation implies it should be created when I init a new project.

**Comment by h3rald** [comment]
Indeed you're right: glyph init does not copy the default CSS files, but it should!

I'll fix it asap, meanwhile you can copy the files manually from here:

http://github.com/h3rald/glyph/tree/master/styles/

Thanks a lot!

**Comment by Jabbslad** [comment]
Thanks man, i sent a pull request for a fork I created. At first I had it so it just copied the default.css then i noticed there was also a css3.css so i changed the rake task to copy all css files using globbing. Hope that helps.

**Comment by h3rald** [comment]
Merged & pushed right now, thanks!
