### ISSUE TITLE
glyph config [key] [value] changes not being persisted to config.yml

### ISSUE THREAD

**Issue by Jabbslad** [h3rald/glyph#95]
glyph config [key] [value] changes do not seem to be persisted to the config.yml (There is no error message).

macbookpro:test jabbslad$ glyph config document.author 'Jamie'
macbookpro:test jabbslad$ cat config.yml | grep 'Jamie'
macbookpro:test jabbslad$

The spec tests are successful as  the examples are not reloading the configuration from config.yml and are referring to the key/vals still held in memory.

**Comment by Jabbslad** [comment]
I've fixed above issue in my fork and sent pull request :)

**Comment by h3rald** [comment]
Looking good Jabbslad, pulled & pushed back up! Thanks!

Closed by 4accfa797e9fe96181c237b2745fd2a97eeadf52.
