### ISSUE TITLE
Ruby 1.9 and UTF-8 encoding

### ISSUE THREAD

**Issue by Jabbslad** [h3rald/glyph#98]
Ruby 1.9 doesn't seem to like the UTF-8 chars in lib/glyph/document.rb
# rake spec

(in /root/temp/glyph)
rake aborted!
/root/temp/glyph/lib/glyph/document.rb:55: invalid multibyte char (US-ASCII)
/root/temp/glyph/lib/glyph/document.rb:55: invalid multibyte char (US-ASCII)
/root/temp/glyph/lib/glyph/document.rb:55: syntax error, unexpected $end, expecting keyword_end
                        key = "â¡â¡â¡â¡â¡PLACEHOLDERÂ¤#{@...
                                 ^
/root/temp/glyph/Rakefile:5:in `require'
(See full trace by running task with --trace)

ruby -v
ruby 1.9.1p376 (2009-12-07 revision 26041) [i686-linux]

**Comment by Jabbslad** [comment]
Apparently the fix is to add following to top of the file containing UTF-8 chars:-

`# encoding: utf-8`

**Comment by h3rald** [comment]
I didn't do any test with Ruby 1.9.1... however, if it can be fixed by adding that line at the top of the relevant files, that's good: I'll fix it asap, or feel free to fix it yourself and I'll pull from your fork.

**Comment by Jabbslad** [comment]
I'll fix it mate

**Comment by h3rald** [comment]
Tested on Linux + Ruby 1.9.1 -- it works!

Closed by c253c528c4cfce4f3f6db7ee7654806fa1a81e0f.
